import io
import unittest

from saslite import SasInterpreter
from saslite.diagnostics.reporter import Reporter


class DataStepRuntimeDiagnosticTests(unittest.TestCase):
    def _run(self, source: str):
        sas = SasInterpreter()
        log = io.StringIO()
        sas._reporter = Reporter(stream=log)
        result = sas.execute(source)
        return sas, result, log.getvalue()

    def test_uninitialized_read_and_generated_missing_are_warnings(self) -> None:
        _, result, log = self._run(
            "data result; calculated=unassigned+1; run;"
        )

        self.assertTrue(result.success, result.error)
        warnings = result.steps[-1].warnings
        self.assertTrue(any("Variable unassigned is uninitialized" in w for w in warnings))
        self.assertTrue(any("Missing value generated by operator +" in w for w in warnings))
        self.assertIn("WARNING:", log)

    def test_assignment_type_conversions_are_explicit_warnings(self) -> None:
        sas, result, _ = self._run(
            """
data result;
  length numeric_value 8 character_value $8;
  numeric_value="12";
  character_value=34;
run;
"""
        )

        self.assertTrue(result.success, result.error)
        warnings = result.steps[-1].warnings
        self.assertTrue(any("character-to-numeric conversion risk" in w for w in warnings))
        self.assertTrue(any("Use INPUT() explicitly" in w for w in warnings))
        self.assertTrue(any("numeric-to-character conversion risk" in w for w in warnings))
        self.assertTrue(any("Use PUT() explicitly" in w for w in warnings))
        frame = sas.get_dataset("WORK", "RESULT")
        self.assertEqual(frame["numeric_value"].iloc[0], "12")
        self.assertEqual(frame["character_value"].iloc[0], 34)

    def test_arithmetic_conversion_and_invalid_numeric_data_are_warned(self) -> None:
        sas, result, _ = self._run(
            """
data result;
  valid="12"+1;
  invalid="not-a-number"*2;
run;
"""
        )

        self.assertTrue(result.success, result.error)
        warnings = result.steps[-1].warnings
        self.assertTrue(any("character-to-numeric conversion" in w for w in warnings))
        self.assertTrue(any("Invalid numeric data 'not-a-number'" in w for w in warnings))

    def test_division_by_zero_is_a_warning_and_missing_result(self) -> None:
        sas, result, _ = self._run(
            "data result; quotient=10/0; run;"
        )

        self.assertTrue(result.success, result.error)
        self.assertTrue(any("division by zero" in w for w in result.steps[-1].warnings))
        value = sas.get_dataset("WORK", "RESULT")["quotient"].iloc[0]
        self.assertNotEqual(value, value)

    def test_invalid_math_function_argument_is_a_warning(self) -> None:
        sas, result, _ = self._run(
            "data result; root=sqrt(-1); logarithm=log(0); run;"
        )

        self.assertTrue(result.success, result.error)
        warnings = result.steps[-1].warnings
        self.assertTrue(any("function SQRT" in warning for warning in warnings))
        self.assertTrue(any("function LOG" in warning for warning in warnings))
        frame = sas.get_dataset("WORK", "RESULT")
        self.assertNotEqual(frame["root"].iloc[0], frame["root"].iloc[0])
        self.assertNotEqual(
            frame["logarithm"].iloc[0],
            frame["logarithm"].iloc[0],
        )

    def test_implicit_conversion_in_comparison_and_concat_is_warned(self) -> None:
        _, result, _ = self._run(
            'data result; compared=("12"=12); joined="ID=" || 12; run;'
        )

        self.assertTrue(result.success, result.error)
        warnings = result.steps[-1].warnings
        self.assertTrue(any(
            "character-to-numeric conversion in comparison" in warning
            for warning in warnings
        ))
        self.assertTrue(any(
            "numeric-to-character conversion in concatenation" in warning
            for warning in warnings
        ))

    def test_repeated_diagnostic_is_aggregated(self) -> None:
        _, result, _ = self._run(
            """
data source;
  input id;
  datalines;
1
2
3
;
run;
data result;
  set source;
  value=never_initialized+id;
run;
"""
        )

        self.assertTrue(result.success, result.error)
        warning = next(
            w for w in result.steps[-1].warnings
            if "Variable never_initialized is uninitialized" in w
        )
        self.assertIn("occurred 3 times", warning)

    def test_conditionally_assigned_variable_is_not_called_uninitialized(self) -> None:
        _, result, _ = self._run(
            """
data result;
  length status $1;
  if 0 then status="Y";
  selected=(status="Y");
run;
"""
        )

        self.assertTrue(result.success, result.error)
        self.assertFalse(any(
            "Variable status is uninitialized" in warning
            for warning in result.steps[-1].warnings
        ))

    def test_missing_input_value_is_not_called_uninitialized(self) -> None:
        _, result, _ = self._run(
            """
data source;
  input value;
  datalines;
.
;
run;
data result;
  set source;
  selected=missing(value);
run;
"""
        )

        self.assertTrue(result.success, result.error)
        self.assertFalse(any(
            "Variable value is uninitialized" in warning
            for warning in result.steps[-1].warnings
        ))

    def test_do_iterator_is_a_compile_time_value_source(self) -> None:
        _, result, _ = self._run(
            """
data result;
  do index=1 to 2;
    output;
  end;
run;
"""
        )

        self.assertTrue(result.success, result.error)
        self.assertFalse(any(
            "Variable index is uninitialized" in warning
            for warning in result.steps[-1].warnings
        ))

    def test_bare_retain_variable_list_does_not_create_initializers(self) -> None:
        _, result, _ = self._run(
            """
data result;
  length first second third $20;
  retain first second third;
  first="a";
  second="b";
  third="c";
run;
"""
        )

        self.assertTrue(result.success, result.error)
        self.assertFalse(result.steps[-1].warnings)

    def test_renamed_input_variables_are_known_to_merge_pdv(self) -> None:
        sas, result, _ = self._run(
            """
data source;
  input id response $;
  datalines;
1 Y
;
run;
data renamed;
  set source;
  rename response=review_response;
  keep id response;
run;
data result;
  merge renamed;
  by id;
  selected=(review_response="Y");
run;
"""
        )

        self.assertTrue(result.success, result.error)
        renamed = sas.get_dataset("WORK", "RENAMED")
        self.assertEqual(
            {str(column).upper() for column in renamed.columns},
            {"ID", "REVIEW_RESPONSE"},
        )
        self.assertFalse(any(
            "review_response is uninitialized" in warning
            for warning in result.steps[-1].warnings
        ))


if __name__ == "__main__":
    unittest.main()
